### ISSUE TITLE
numpy.AxisError: axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by gireeshkbogu** [karan-shr/DEXTR-AnnoTool#1]
Hi, I am getting the following error when I try to run it on greyscale images. Any help would be appreciated. 

```
$ python annotate.py -c anno_cfg.yml
Using TensorFlow backend.
In config file 'update: True', so source folder will be scanned again and new files will be added to progress tracking cache.
WARNING: Logging before flag parsing goes to stderr.
W0719 10:29:04.516912 140735883694976 deprecation_wrapper.py:119] From annotate.py:50: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-07-19 10:29:04.528869: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
W0719 10:29:04.529401 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0719 10:29:04.529595 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0719 10:29:04.532835 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0719 10:29:04.551954 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0719 10:29:04.571941 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

W0719 10:29:04.633628 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Building network based on ResNet 101 and PSP module expecting inputs of shape (512, 512) predicting 1 classes
PSP module will interpolate to a final feature map size of (64, 64)
W0719 10:29:13.033720 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/miniconda2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

W0719 10:29:13.107793 140735883694976 deprecation_wrapper.py:119] From /Users/gireeshbogu/Desktop/DEXTR-AnnoTool/networks/classifiers.py:26: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

Loading weights from H5 file.
Traceback (most recent call last):
  File "annotate.py", line 151, in <module>
    input_dextr = np.concatenate((resize_image, extreme_heatmap[:, :, np.newaxis]), axis=2)
numpy.AxisError: axis 2 is out of bounds for array of dimension 2
```
I tried changing the axis to 1 and then got the following error.
`ValueError: all the input arrays must have the same number of dimensions
`
I tried np.column_stack instead of np.concatenate and got the following error. 
`TypeError: column_stack() got an unexpected keyword argument 'axis'
`
I tried np.appennd annd got the following error.
`TypeError: append() missing 1 required positional argument: 'values'`

**Comment by gireeshkbogu** [comment]
I tried to upgrade TF and able to get rid of some errors but not all. 

` pip install --ignore-installed --upgrade https://github.com/lakshayg/tensorflow-build/releases/download/tf1.9.0-macos-py27-py36/tensorflow-1.9.0-cp36-cp36m-macosx_10_13_x86_64.whl`

```
$ python annotate.py -c anno_cfg.yml
Using TensorFlow backend.
In config file 'update: True', so source folder will be scanned again and new files will be added to progress tracking cache.
Building network based on ResNet 101 and PSP module expecting inputs of shape (512, 512) predicting 1 classes
PSP module will interpolate to a final feature map size of (64, 64)
Loading weights from H5 file.
Traceback (most recent call last):
  File "annotate.py", line 151, in <module>
    input_dextr = np.concatenate((resize_image, extreme_heatmap[:, :, np.newaxis]), axis=2)
numpy.AxisError: axis 2 is out of bounds for array of dimension 2
```

**Comment by clementcheuk** [comment]
I tried to update tf to 1.13.1 and get the following message:
'''sh 
$ python annotate.py -c anno_cfg.yml
Using TensorFlow backend.
In config file 'update: True', so source folder will be scanned again and new files will be added to progress tracking cache.
2019-10-23 16:48:21.316237: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-10-23 16:48:21.316266: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-10-23 16:48:21.316288: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-10-23 16:48:21.316353: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-10-23 16:48:21.316359: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Building network based on ResNet 101 and PSP module expecting inputs of shape (512, 512) predicting 1 classes
PSP module will interpolate to a final feature map size of (64, 64)
Loading weights from H5 file.
Traceback (most recent call last):
  File "annotate.py", line 61, in <module>
    plt.switch_backend('TkAgg')  # force 'TkAgg' backend
  File "/opt/dextr_cgdb/miniconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 230, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
'''
